/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend.TablaProductos;

import Backend.BotConsultas.BootConsultas;
import InstanciaADMIN.InstanciaADMIN;
import RSMaterialComponent.RSComboBox;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Huáscar
 */
public class DialogAñadir extends javax.swing.JDialog {

    public static ArrayList dataCliente;
    public static int id;
    private String query;
    BootConsultas Bot = InstanciaADMIN.Bot;
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    public static ArrayList dataToShow;

    /**
     * Creates new form DialogAñadir
     */
    public DialogAñadir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getDataClient();
//        getDataCliente(true);
        setLocationRelativeTo(null);

    }

    public void validarAndCrear() {
        Date validoHasta;
        String fechasHasta = "";
        if (this.validoHasta.getDate() != null) {
            String formato = "dd MMMM yyyy";
            validoHasta = this.validoHasta.getDate();
            SimpleDateFormat formateador = new SimpleDateFormat(formato);
            fechasHasta = (String) String.valueOf(formateador.format(validoHasta));
        }

        String nombre = this.TxtNombreA.getText();
        int costoInicial = (int) this.SpinnerI.getValue();
        int interes = (int) this.SpinnerF.getValue();

        int costoFinal = interes + costoInicial;

        String idCliente = String.valueOf(ComboClient.getSelectedItem());

        System.out.println(idCliente);

        String[] campos = {nombre, fechasHasta, String.valueOf(costoInicial), String.valueOf(costoFinal), String.valueOf(interes), idCliente};
        boolean validate = true;

        for (String value : campos) {
            if (value.length() < 0) {
                validate = false;
            }
        }

        if (validate) {
            AbstraccionProductos.agregarProducto(campos);

        } else {
            JOptionPane.showMessageDialog(this, "faltan campos");
        }

    }

    public void getDataClient() {

        String query = " SELECT cliente.id, cliente.nombre, cliente.telefono , cliente.email\n"
                +"FROM cliente";

        if (InstanciaADMIN.Bot.getClientes(query)) {
            ArrayList<Object[]> dataToShow = InstanciaADMIN.Bot.getDataClienteOrClientes();
            for (Object d[] : dataToShow) {
                this.model.addElement(d[0]);
                System.out.println(dataToShow);
                ComboClient.addItem(d[0]);
                ComboClient.setModel(this.model);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Fallo en la consulta");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackBtn = new RSMaterialComponent.RSButtonMaterialShadow();
        Agregar_art = new RSMaterialComponent.RSButtonMaterialTwo();
        TxtNombreA = new necesario.TextField();
        validoHasta = new newscomponents.RSDateChooser();
        SpinnerF = new javax.swing.JSpinner();
        ComboClient = new RSMaterialComponent.RSComboBox();
        SpinnerI = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(670, 470));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(670, 470));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        BackBtn.setBackground(new java.awt.Color(255, 51, 51));
        BackBtn.setText("Volver atras");
        BackBtn.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn);
        BackBtn.setBounds(504, 0, 160, 40);

        Agregar_art.setBackground(new java.awt.Color(0, 204, 255));
        Agregar_art.setText("Agregar articulo");
        Agregar_art.setBackgroundHover(new java.awt.Color(102, 153, 255));
        Agregar_art.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        Agregar_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_artActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar_art);
        Agregar_art.setBounds(210, 340, 187, 38);

        TxtNombreA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(51, 102, 255), new java.awt.Color(51, 102, 255), new java.awt.Color(51, 102, 255)));
        TxtNombreA.setForeground(new java.awt.Color(51, 102, 255));
        TxtNombreA.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        TxtNombreA.setPlaceholder("Añade nombre de articulo");
        jPanel1.add(TxtNombreA);
        TxtNombreA.setBounds(250, 120, 200, 29);

        validoHasta.setBackground(new java.awt.Color(51, 102, 255));
        validoHasta.setBgColor(new java.awt.Color(51, 102, 255));
        validoHasta.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jPanel1.add(validoHasta);
        validoHasta.setBounds(250, 150, 290, 26);

        SpinnerF.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        SpinnerF.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 100));
        SpinnerF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255)));
        jPanel1.add(SpinnerF);
        SpinnerF.setBounds(220, 190, 140, 32);

        ComboClient.setBackground(new java.awt.Color(51, 102, 255));
        ComboClient.setColorArrow(new java.awt.Color(51, 102, 255));
        ComboClient.setColorBorde(new java.awt.Color(51, 102, 255));
        ComboClient.setColorFondo(new java.awt.Color(51, 102, 255));
        ComboClient.setColorSeleccion(new java.awt.Color(51, 102, 255));
        ComboClient.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jPanel1.add(ComboClient);
        ComboClient.setBounds(220, 260, 200, 23);

        SpinnerI.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        SpinnerI.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 100));
        SpinnerI.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255)));
        jPanel1.add(SpinnerI);
        SpinnerI.setBounds(220, 220, 140, 32);

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel6.setText("Nombre de articulo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 120, 140, 20);

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel7.setText("Fecha limite ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 160, 100, 20);

        jLabel8.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel8.setText("Costo inicial");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 190, 100, 20);

        jLabel9.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel9.setText("Interés");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 220, 60, 20);

        jLabel10.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel10.setText("Cliente");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(130, 260, 70, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed

        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void Agregar_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_artActionPerformed
        validarAndCrear();
    }//GEN-LAST:event_Agregar_artActionPerformed

    public void alerta(String Mensaje) {
        JOptionPane.showMessageDialog(null, Mensaje);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAñadir dialog = new DialogAñadir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialTwo Agregar_art;
    private RSMaterialComponent.RSButtonMaterialShadow BackBtn;
    private RSMaterialComponent.RSComboBox ComboClient;
    private javax.swing.JSpinner SpinnerF;
    private javax.swing.JSpinner SpinnerI;
    private necesario.TextField TxtNombreA;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private newscomponents.RSDateChooser validoHasta;
    // End of variables declaration//GEN-END:variables
}
