/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend.TablaProductos;

import Backend.BotConsultas.BootConsultas;
import InstanciaADMIN.InstanciaADMIN;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huáscar
 */
public class Productoss extends javax.swing.JFrame {

    /**
     * Creates new form Productoss
     */
   public Productoss() {
        initComponents();
        setModel();
        actualizarData();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public static int id;
    private String query;
    public static ArrayList <Object[]> dataProducto;
    public static DefaultTableModel model;
    BootConsultas Bot = InstanciaADMIN.Bot;
    
    private void setModel() {

        Vector columnas = new Vector<String>();
        columnas.addElement("id");
        columnas.addElement("Nombre de producto");
        columnas.addElement("Valio hasta");
        columnas.addElement("Interes");
        columnas.addElement("Costo inicial");
        columnas.addElement("Costo final");
        columnas.addElement("Cliente");
        Vector filas = new Vector<Object[]>();
        
        model = new DefaultTableModel(filas, columnas);
        tabe.setModel(model);
    }
    
    public void actualizarData() {
        AbstraccionProductos.limpiarTabla(this.model);
        AbstraccionProductos.getDataProducto(this.model);
        AbstraccionProductos.mostrarProduct(this.model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabe = new RSMaterialComponent.RSTableMetroCustom();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        VolerProduct = new RSMaterialComponent.RSButtonMaterialShadow();
        EditarBtn = new RSMaterialComponent.RSButtonMaterialTwo();
        Eliminar = new RSMaterialComponent.RSButtonMaterialShadow();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 470));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(880, 470));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tabe.setForeground(new java.awt.Color(0, 0, 0));
        tabe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabe.setBackgoundHead(new java.awt.Color(51, 102, 255));
        tabe.setBackgoundHover(new java.awt.Color(51, 102, 255));
        tabe.setColorBorderHead(new java.awt.Color(0, 204, 255));
        tabe.setColorBorderRows(new java.awt.Color(0, 204, 255));
        tabe.setColorPrimaryText(new java.awt.Color(51, 102, 255));
        tabe.setColorSecondary(new java.awt.Color(255, 255, 255));
        tabe.setColorSecundaryText(new java.awt.Color(51, 102, 255));
        tabe.setFont(new java.awt.Font("Dubai Medium", 1, 11)); // NOI18N
        tabe.setFontHead(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        tabe.setFontRowHover(new java.awt.Font("Dubai Medium", 1, 11)); // NOI18N
        tabe.setFontRowSelect(new java.awt.Font("Dubai Medium", 1, 11)); // NOI18N
        jScrollPane2.setViewportView(tabe);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(230, 150, 640, 310);

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventario.png"))); // NOI18N
        jLabel2.setText("Articulos");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 20, 350, 100);

        VolerProduct.setBackground(new java.awt.Color(255, 51, 51));
        VolerProduct.setText("Volver atras");
        VolerProduct.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        VolerProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolerProductActionPerformed(evt);
            }
        });
        jPanel3.add(VolerProduct);
        VolerProduct.setBounds(720, 0, 160, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 880, 150);

        EditarBtn.setBackground(new java.awt.Color(51, 102, 255));
        EditarBtn.setText("Editar articulo");
        EditarBtn.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        EditarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(EditarBtn);
        EditarBtn.setBounds(10, 170, 200, 50);

        Eliminar.setBackground(new java.awt.Color(255, 51, 51));
        Eliminar.setText("Eliminar articulo");
        Eliminar.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar);
        Eliminar.setBounds(10, 240, 200, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolerProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolerProductActionPerformed
        InstanciaADMIN.Productoss.dataProducto.clear();
        this.dispose();
    }//GEN-LAST:event_VolerProductActionPerformed

    private void EditarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBtnActionPerformed
        if (AbstraccionProductos.updateProducto(tabe)) {
            AbstraccionProductos.alerta("actualizado correctamente ( la tabla es editable) ! ");
        } else {
            AbstraccionProductos.alerta("favor de seleccionar un producto (la tabla es editable)");
        }
    }//GEN-LAST:event_EditarBtnActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (AbstraccionProductos.eliminarProducto(this.tabe)) {
            AbstraccionProductos.alerta("Eliminando correctamente");
        } else {
            AbstraccionProductos.alerta("Favor de seleccionar un producto ");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productoss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialTwo EditarBtn;
    private RSMaterialComponent.RSButtonMaterialShadow Eliminar;
    private RSMaterialComponent.RSButtonMaterialShadow VolerProduct;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSTableMetroCustom tabe;
    // End of variables declaration//GEN-END:variables
}
