/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend.Login;

import Frontend.Inicio.Inicioo;
import Frontend.Registro.Registro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import InstanciaADMIN.InstanciaADMIN ; 
/**
 *
 * @author edisonjpp
 */
public class Login extends javax.swing.JFrame {
 
    
    public Login() {
        initComponents();
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
         this.setLocationRelativeTo(null);
        setVisible(true);

    }

    public void verificarCampos() {
        if (rSPasswordMaterialIcon1.getText().length() < 1 || rSTextFieldMaterialIcon1.getText().length() < 1) {
            JOptionPane.showMessageDialog(this, "Favor de llenar todos los campos");
        } else {
            String query = "SELECT * FROM registro_admin\n"
                    + "WHERE nombre_usuario = " + "'" + rSTextFieldMaterialIcon1.getText() + "'\n"
                    + "AND pass = "+ " '"+rSPasswordMaterialIcon1.getText() + "'";

//            BootConsultas consulta = new BootConsultas(query);
            
            if (InstanciaADMIN.Bot.validarUsuario(query)) {
                ArrayList<String> dataCruda = InstanciaADMIN.Bot.getData();
                hacerLogin(dataCruda);
            }

        }
    }

    private void hacerLogin(ArrayList<String> data) {

        if (data.size() > 0) {
                System.out.println(" " + data);
                 System.out.println(" " + data.get(1));
                  System.out.println(" " + data.get(2));
            if (rSTextFieldMaterialIcon1.getText().equals(data.get(1)) && rSPasswordMaterialIcon1.getText().equals(data.get(2))) {
                JOptionPane.showMessageDialog(this, "Haz iniciado session correctamente");
                this.setVisible(false);
                InstanciaADMIN.Inicio = new Inicioo(Integer.parseInt(data.get(0))); 
//                InstanciaADMIN.MuroDelCliente = new MuroDelCliente(1);
            }else{
                JOptionPane.showMessageDialog(this, "hola");                        
            }
        } else {
            JOptionPane.showMessageDialog(null, "Datos Incorrectos!");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSAnimation1 = new rojeru_san.complementos.RSAnimation();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        rSButtonShape1 = new RSMaterialComponent.RSButtonShape();
        rSPasswordMaterialIcon1 = new RSMaterialComponent.RSPasswordMaterialIcon();
        jLabel2 = new javax.swing.JLabel();
        rSTextFieldMaterialIcon1 = new RSMaterialComponent.RSTextFieldMaterialIcon();
        rSButtonMaterialShadow3 = new RSMaterialComponent.RSButtonMaterialShadow();
        rSButtonMaterialTwo2 = new RSMaterialComponent.RSButtonMaterialTwo();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel2.setLayout(null);

        rSButtonShape1.setBackground(new java.awt.Color(51, 102, 255));
        rSButtonShape1.setBorder(null);
        rSButtonShape1.setText("Entrar");
        rSButtonShape1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        rSButtonShape1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShape1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonShape1);
        rSButtonShape1.setBounds(213, 250, 250, 42);

        rSPasswordMaterialIcon1.setColorIcon(new java.awt.Color(51, 102, 255));
        rSPasswordMaterialIcon1.setColorMaterial(new java.awt.Color(51, 102, 255));
        rSPasswordMaterialIcon1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        rSPasswordMaterialIcon1.setPlaceholder("Password");
        jPanel2.add(rSPasswordMaterialIcon1);
        rSPasswordMaterialIcon1.setBounds(213, 190, 250, 42);

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Iniciar Sesion");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(242, 82, 148, 42);

        rSTextFieldMaterialIcon1.setForeground(new java.awt.Color(51, 102, 255));
        rSTextFieldMaterialIcon1.setColorIcon(new java.awt.Color(51, 102, 255));
        rSTextFieldMaterialIcon1.setColorMaterial(new java.awt.Color(51, 102, 255));
        rSTextFieldMaterialIcon1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        rSTextFieldMaterialIcon1.setPlaceholder("Usuario");
        rSTextFieldMaterialIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterialIcon1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSTextFieldMaterialIcon1);
        rSTextFieldMaterialIcon1.setBounds(213, 142, 250, 42);

        rSButtonMaterialShadow3.setBackground(new java.awt.Color(255, 51, 51));
        rSButtonMaterialShadow3.setText("Salir");
        rSButtonMaterialShadow3.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        rSButtonMaterialShadow3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialShadow3ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialShadow3);
        rSButtonMaterialShadow3.setBounds(540, 0, 160, 40);

        rSButtonMaterialTwo2.setBackground(new java.awt.Color(0, 204, 255));
        rSButtonMaterialTwo2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rSButtonMaterialTwo2.setText("Registrate");
        rSButtonMaterialTwo2.setActionCommand("Regístrate");
        rSButtonMaterialTwo2.setBackgroundHover(new java.awt.Color(102, 153, 255));
        rSButtonMaterialTwo2.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        rSButtonMaterialTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialTwo2);
        rSButtonMaterialTwo2.setBounds(270, 310, 130, 40);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Copyright  @Edison & Huascard 2020");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 410, 700, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonShape1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShape1ActionPerformed
        this.verificarCampos();
    }//GEN-LAST:event_rSButtonShape1ActionPerformed

    private void rSTextFieldMaterialIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterialIcon1ActionPerformed

    }//GEN-LAST:event_rSTextFieldMaterialIcon1ActionPerformed

    private void rSButtonMaterialShadow3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialShadow3ActionPerformed
        System.exit(0);

    }//GEN-LAST:event_rSButtonMaterialShadow3ActionPerformed

    private void rSButtonMaterialTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo2ActionPerformed
        this.dispose();
        InstanciaADMIN.Registro = new Registro();
    }//GEN-LAST:event_rSButtonMaterialTwo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private rojeru_san.complementos.RSAnimation rSAnimation1;
    private RSMaterialComponent.RSButtonMaterialShadow rSButtonMaterialShadow3;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo2;
    private RSMaterialComponent.RSButtonShape rSButtonShape1;
    private RSMaterialComponent.RSPasswordMaterialIcon rSPasswordMaterialIcon1;
    private RSMaterialComponent.RSTextFieldMaterialIcon rSTextFieldMaterialIcon1;
    // End of variables declaration//GEN-END:variables
}
