/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend.Inicio;

import Frontend.ClientesView.ClientesMain;
import Frontend.Login.Login;
import Frontend.MuroDelCliente.Addcliente;
import Frontend.Registro.Registro;
import Frontend.TablaProductos.DialogAñadir;
import Frontend.TablaProductos.Productoss;
import java.awt.Dimension;
import InstanciaADMIN.InstanciaADMIN;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Huáscar
 */
public class Inicioo extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    /**
     * Creates new form Inicioo
     */
    public Inicioo(int id) {
        this.idAdmin = id;
        initComponents();
        bigpane.setPreferredSize(new Dimension(663, 585));
        bigpane.setMinimumSize(new Dimension(663, 585));
        this.setLocationRelativeTo(null);
        datosDeLaEmpresa();
        setVisible(true);
    }
    ArrayList<String> datosDeEmpresa;
    ArrayList<String> datosDeAdmin;
    int idAdmin;
    int countProduct ; 

    private void datosDeLaEmpresa() {
        String query = "SELECT * FROM tienda_empeno ";

        String query2 = "SELECT * FROM registro_admin WHERE id = " + this.idAdmin;

        String query3 = "SELECT COUNT(*) AS cantidad_productos FROM producto ";

        if (InstanciaADMIN.Bot.getDatosDeLaEmpresa(query) && InstanciaADMIN.Bot.validarUsuario(query2)
                && InstanciaADMIN.Bot.getCantidadDeProductos(query3)) {
            
            datosDeEmpresa = InstanciaADMIN.Bot.getDataEmpresa(); /// este nop ..... verifiquemos 
            datosDeAdmin = InstanciaADMIN.Bot.getData(); // este se obtiene . 
            countProduct = InstanciaADMIN.Bot.getCantidadProductos(); //// este nop ;
            System.out.println(datosDeEmpresa);
             System.out.println(datosDeAdmin);
              System.out.println(datosDeEmpresa);
            if (datosDeEmpresa.size() > 0 && datosDeAdmin.size() > 0) {
                showDatos();
            } else {
                JOptionPane.showMessageDialog(this, "no trajo nada");
            }
        }
    }

    private void showDatos() {
        this.jLabel3.setText(this.datosDeEmpresa.get(1));
        this.jLabel13.setText(this.datosDeEmpresa.get(3));
        this.jLabel20.setText(this.datosDeEmpresa.get(4));
        this.jSpinner1.setValue(Integer.parseInt(this.datosDeEmpresa.get(2)));
        this.jSpinner2.setValue(this.countProduct);
        jLabel7.setText(this.datosDeAdmin.get(1));
        jLabel2.setText(this.datosDeAdmin.get(3));
    }
    
    public void cerrar(boolean cierto){
        this.setVisible(cierto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bigpane = new javax.swing.JPanel();
        BtnAñadirCliente = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtnMuroArticulos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        BtnAddarticles = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        BtnMuroCliente = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        rSButtonMaterialTwo1 = new RSMaterialComponent.RSButtonMaterialTwo();
        rSButtonMaterialTwo2 = new RSMaterialComponent.RSButtonMaterialTwo();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DragLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 760));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1300, 760));
        getContentPane().setLayout(null);

        bigpane.setBackground(new java.awt.Color(255, 255, 255));
        bigpane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bigpane.setMinimumSize(new java.awt.Dimension(1280, 720));
        bigpane.setLayout(null);

        BtnAñadirCliente.setBackground(new java.awt.Color(0, 204, 255));
        BtnAñadirCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        BtnAñadirCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAñadirClienteMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Addcliente.png"))); // NOI18N

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" Añadir cliente");

        javax.swing.GroupLayout BtnAñadirClienteLayout = new javax.swing.GroupLayout(BtnAñadirCliente);
        BtnAñadirCliente.setLayout(BtnAñadirClienteLayout);
        BtnAñadirClienteLayout.setHorizontalGroup(
            BtnAñadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnAñadirClienteLayout.createSequentialGroup()
                .addGroup(BtnAñadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BtnAñadirClienteLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel8))
                    .addGroup(BtnAñadirClienteLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel16)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnAñadirClienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        BtnAñadirClienteLayout.setVerticalGroup(
            BtnAñadirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnAñadirClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bigpane.add(BtnAñadirCliente);
        BtnAñadirCliente.setBounds(390, 180, 310, 230);

        BtnMuroArticulos.setBackground(new java.awt.Color(0, 204, 255));
        BtnMuroArticulos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        BtnMuroArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMuroArticulosMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventario.png"))); // NOI18N

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ver articulos");

        javax.swing.GroupLayout BtnMuroArticulosLayout = new javax.swing.GroupLayout(BtnMuroArticulos);
        BtnMuroArticulos.setLayout(BtnMuroArticulosLayout);
        BtnMuroArticulosLayout.setHorizontalGroup(
            BtnMuroArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnMuroArticulosLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnMuroArticulosLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        BtnMuroArticulosLayout.setVerticalGroup(
            BtnMuroArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnMuroArticulosLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        bigpane.add(BtnMuroArticulos);
        BtnMuroArticulos.setBounds(760, 460, 310, 230);

        BtnAddarticles.setBackground(new java.awt.Color(0, 204, 255));
        BtnAddarticles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        BtnAddarticles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAddarticlesMouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Empeñar.png"))); // NOI18N

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Empeñar");

        javax.swing.GroupLayout BtnAddarticlesLayout = new javax.swing.GroupLayout(BtnAddarticles);
        BtnAddarticles.setLayout(BtnAddarticlesLayout);
        BtnAddarticlesLayout.setHorizontalGroup(
            BtnAddarticlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnAddarticlesLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(BtnAddarticlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addGroup(BtnAddarticlesLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addGap(0, 89, Short.MAX_VALUE))
        );
        BtnAddarticlesLayout.setVerticalGroup(
            BtnAddarticlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnAddarticlesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BtnAddarticlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnAddarticlesLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnAddarticlesLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addGap(84, 84, 84))))
        );

        bigpane.add(BtnAddarticles);
        BtnAddarticles.setBounds(390, 460, 310, 230);

        BtnMuroCliente.setBackground(new java.awt.Color(0, 204, 255));
        BtnMuroCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        BtnMuroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMuroClienteMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/client.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Ver clientes");

        javax.swing.GroupLayout BtnMuroClienteLayout = new javax.swing.GroupLayout(BtnMuroCliente);
        BtnMuroCliente.setLayout(BtnMuroClienteLayout);
        BtnMuroClienteLayout.setHorizontalGroup(
            BtnMuroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnMuroClienteLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(BtnMuroClienteLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BtnMuroClienteLayout.setVerticalGroup(
            BtnMuroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnMuroClienteLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        bigpane.add(BtnMuroCliente);
        BtnMuroCliente.setBounds(760, 180, 310, 230);

        jPanel19.setBackground(new java.awt.Color(51, 102, 255));
        jPanel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        jPanel19.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Articulos:");
        jPanel19.add(jLabel19);
        jLabel19.setBounds(700, 80, 110, 20);

        jLabel17.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Presupuesto:");
        jPanel19.add(jLabel17);
        jLabel17.setBounds(700, 110, 120, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shutdown.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel19.add(jLabel10);
        jLabel10.setBounds(1070, 0, 50, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minmize.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel19.add(jLabel1);
        jLabel1.setBounds(1020, 0, 50, 40);

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REAL NOMBRE EMPRESA");
        jPanel19.add(jLabel3);
        jLabel3.setBounds(10, 0, 330, 42);

        jSpinner1.setEnabled(false);
        jPanel19.add(jSpinner1);
        jSpinner1.setBounds(850, 110, 170, 20);

        jSpinner2.setEnabled(false);
        jPanel19.add(jSpinner2);
        jSpinner2.setBounds(850, 80, 170, 20);

        jLabel13.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("809 997 3338");
        jPanel19.add(jLabel13);
        jLabel13.setBounds(20, 70, 240, 16);

        jLabel14.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("casadeempeno@gmail.com");
        jPanel19.add(jLabel14);
        jLabel14.setBounds(20, 40, 240, 32);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("jlabel20");
        jPanel19.add(jLabel20);
        jLabel20.setBounds(130, 100, 270, 22);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Direccion: ");
        jPanel19.add(jLabel21);
        jLabel21.setBounds(20, 100, 100, 22);

        bigpane.add(jPanel19);
        jPanel19.setBounds(180, 0, 1120, 150);

        jPanel20.setBackground(new java.awt.Color(51, 102, 255));
        jPanel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        jPanel20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(null);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Addadmin.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel20.add(jLabel26);
        jLabel26.setBounds(20, 10, 110, 100);

        rSButtonMaterialTwo1.setBackground(new java.awt.Color(255, 0, 0));
        rSButtonMaterialTwo1.setText("Cerrar sesión");
        rSButtonMaterialTwo1.setBackgroundHover(new java.awt.Color(255, 51, 51));
        rSButtonMaterialTwo1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        rSButtonMaterialTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo1ActionPerformed(evt);
            }
        });
        jPanel20.add(rSButtonMaterialTwo1);
        rSButtonMaterialTwo1.setBounds(-10, 300, 210, 50);

        rSButtonMaterialTwo2.setBackground(new java.awt.Color(0, 204, 255));
        rSButtonMaterialTwo2.setText("Admin info");
        rSButtonMaterialTwo2.setBackgroundHover(new java.awt.Color(102, 153, 255));
        rSButtonMaterialTwo2.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        rSButtonMaterialTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo2ActionPerformed(evt);
            }
        });
        jPanel20.add(rSButtonMaterialTwo2);
        rSButtonMaterialTwo2.setBounds(10, 190, 160, 50);

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefono Admin");
        jPanel20.add(jLabel2);
        jLabel2.setBounds(20, 150, 150, 20);

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre del AMDMIN");
        jPanel20.add(jLabel7);
        jLabel7.setBounds(20, 120, 140, 24);
        jPanel20.add(jSeparator1);
        jSeparator1.setBounds(0, 250, 210, 20);

        bigpane.add(jPanel20);
        jPanel20.setBounds(0, 150, 180, 580);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/casa-de-empeno.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bigpane.add(jPanel1);
        jPanel1.setBounds(0, 0, 180, 150);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Copyright  @Edison & Huascard 2020");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(423, 423, 423))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        bigpane.add(jPanel2);
        jPanel2.setBounds(180, 700, 1120, 30);

        getContentPane().add(bigpane);
        bigpane.setBounds(0, 1, 1300, 730);

        DragLabel.setText("jLabel4");
        DragLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragLabelMouseDragged(evt);
            }
        });
        DragLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DragLabelMousePressed(evt);
            }
        });
        getContentPane().add(DragLabel);
        DragLabel.setBounds(0, 0, 1280, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
//        this.dispose();
          System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void rSButtonMaterialTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo1ActionPerformed
        this.dispose();

        InstanciaADMIN.Login = new Login();
    }//GEN-LAST:event_rSButtonMaterialTwo1ActionPerformed

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        InstanciaADMIN.Registro = new Registro();
    }//GEN-LAST:event_jLabel26MouseClicked

    private void BtnMuroArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMuroArticulosMouseClicked
        InstanciaADMIN.Productoss = new Productoss();
    }//GEN-LAST:event_BtnMuroArticulosMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
//        this.getRootPane().setWindowDecorationStyle(PLAIN_DIALOG);
//        this.setExtendedState(MAXIMIZED_BOTH);  //Maximizing the frame
        this.setExtendedState(ICONIFIED | getExtendedState());
    }//GEN-LAST:event_jLabel1MouseClicked

    private void rSButtonMaterialTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo2ActionPerformed
        InstanciaADMIN.MuroADMINDialog = new MuroADMINDialog(this.datosDeAdmin);
    }//GEN-LAST:event_rSButtonMaterialTwo2ActionPerformed

    private void BtnMuroClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMuroClienteMouseClicked
       InstanciaADMIN.ClientesMain = new ClientesMain();
       cerrar(false);
      
    }//GEN-LAST:event_BtnMuroClienteMouseClicked

    private void BtnAñadirClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAñadirClienteMouseClicked
        new Addcliente(this, true).setVisible(true);
    }//GEN-LAST:event_BtnAñadirClienteMouseClicked

    private void BtnAddarticlesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAddarticlesMouseClicked
        new DialogAñadir(this, true).setVisible(true);
    }//GEN-LAST:event_BtnAddarticlesMouseClicked

    private void DragLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragLabelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_DragLabelMouseDragged

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
       
    }//GEN-LAST:event_jLabel15MousePressed

    private void DragLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragLabelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_DragLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicioo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicioo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicioo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicioo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new Inicioo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnAddarticles;
    private javax.swing.JPanel BtnAñadirCliente;
    private javax.swing.JPanel BtnMuroArticulos;
    private javax.swing.JPanel BtnMuroCliente;
    private javax.swing.JLabel DragLabel;
    private javax.swing.JPanel bigpane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JSpinner jSpinner1;
    public javax.swing.JSpinner jSpinner2;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo1;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo2;
    // End of variables declaration//GEN-END:variables
}
