/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend.Registro;

import Frontend.Login.Login;
import InstanciaADMIN.InstanciaADMIN;
import javax.swing.JOptionPane;

/**
 *
 * @author Huáscar
 */
public class Registro extends javax.swing.JFrame{

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSTextFieldIconTwo1 = new RSMaterialComponent.RSTextFieldIconTwo();
        rSTextFieldMaterial1 = new RSMaterialComponent.RSTextFieldMaterial();
        rSTextFieldTwo1 = new RSMaterialComponent.RSTextFieldTwo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Out = new RSMaterialComponent.RSButtonMaterialShadow();
        jLabel1 = new javax.swing.JLabel();
        PassField = new necesario.PassField();
        TxtUser = new necesario.TextField();
        PassFieldC = new necesario.PassField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtTel = new necesario.TextField();
        RegistrarYvalidar = new RSMaterialComponent.RSButtonMaterialTwo();

        rSTextFieldIconTwo1.setText("rSTextFieldIconTwo1");

        rSTextFieldMaterial1.setText("rSTextFieldMaterial1");

        rSTextFieldTwo1.setText("rSTextFieldTwo1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registro de Administradores.____");

        Out.setBackground(new java.awt.Color(255, 51, 51));
        Out.setText("Salir");
        Out.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Out, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Out, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Usuario:");

        PassField.setForeground(new java.awt.Color(51, 102, 255));
        PassField.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        PassField.setPlaceholder("Escribe tu contraseña");
        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });

        TxtUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TxtUser.setForeground(new java.awt.Color(51, 102, 255));
        TxtUser.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        TxtUser.setPlaceholder("Escribe tu usuario");
        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });

        PassFieldC.setForeground(new java.awt.Color(51, 102, 255));
        PassFieldC.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        PassFieldC.setPlaceholder("Confirma tu contraseña");
        PassFieldC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldCActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 204, 255));
        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Telefono:");

        jLabel3.setBackground(new java.awt.Color(0, 204, 255));
        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Confirmar contraseña:");

        jLabel4.setBackground(new java.awt.Color(0, 204, 255));
        jLabel4.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Contraseña:");

        TxtTel.setBorder(null);
        TxtTel.setForeground(new java.awt.Color(51, 102, 255));
        TxtTel.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        TxtTel.setPlaceholder("Escribe tu teléfono");
        TxtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelActionPerformed(evt);
            }
        });

        RegistrarYvalidar.setBackground(new java.awt.Color(51, 102, 255));
        RegistrarYvalidar.setText("Registrar");
        RegistrarYvalidar.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        RegistrarYvalidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarYvalidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(127, 127, 127)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PassFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(RegistrarYvalidar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PassFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RegistrarYvalidar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutActionPerformed
        this.dispose();
        InstanciaADMIN.Login = new Login();
    }//GEN-LAST:event_OutActionPerformed

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFieldActionPerformed

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUserActionPerformed

    private void PassFieldCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFieldCActionPerformed

    private void TxtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelActionPerformed

    private void RegistrarYvalidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarYvalidarActionPerformed
//       registrarYvalidar();
       String user = TxtUser.getText();
       String teI = TxtTel.getText();
       String pass = new String(PassField.getPassword());
       String passCon = new String(PassFieldC.getPassword());
       
        if(TxtUser.equals("") || pass.equals("") || passCon.equals("") || TxtTel.equals("")){
          
            JOptionPane.showMessageDialog(null, "Hay campos vacios");
        }
       
       String query = "INSERT INTO registro_admin (nombre_usuario, pass, telefono)\n"
        + " VALUES ('"+ user + "','" + pass + "' ,'" + teI + "')";  
       String queryVa = "SELECT nombre_usuario FROM registro_admin WHERE nombre_usuario = '"+ user + "' ";
       
       
        if(pass.equals(passCon)){ 
            
            if(InstanciaADMIN.Bot.validarUsuario(queryVa) == true){
                
                if(InstanciaADMIN.Bot.getData().isEmpty()){
                    
                    if(InstanciaADMIN.Bot.bootAgregarEliminarActualizar(query) == true){
                       Alerta("Registrado con exito");
                       limpiar();
                       this.dispose();
                       InstanciaADMIN.Login = new Login();
                       
                    }else{
                       Alerta("Error de registro");
                    }
                }else  
                    Alerta("El usuario ya existe");
                    limpiar();
            }else{
                Alerta("El usuario ya existe");
                limpiar();
            }        
        }else{
            Alerta("Las contraseñas no coinciden");
        }
    }//GEN-LAST:event_RegistrarYvalidarActionPerformed

//    public void registrarYvalidar(){
//       String user = TxtUser.getText();
//       String teI = TxtTel.getText();
//       String pass = new String(PassField.getPassword());
//       String passCon = new String(PassFieldC.getPassword());
//       
//        if(TxtUser.equals("") || pass.equals("") || passCon.equals("") || TxtTel.equals("")){
//          
//            JOptionPane.showMessageDialog(null, "Hay campos vacios");
//        }
//       
//       String query = "INSERT INTO registro_admin (nombre_usuario, pass, telefono)\n"
//        + " VALUES ('"+ user + "','" + pass + "' ,'" + teI + "')";  
//       
//       String queryVa = "SELECT nombre_usuario FROM registro_admin WHERE nombre_usuario = '"+ user + "' ";
//       
//       
//        if(pass.equals(passCon)){ 
//            
//            if(InstanciaADMIN.Bot.validarUsuario(queryVa) == true){
//                
//                if(InstanciaADMIN.Bot.getData().isEmpty()){
//                    
//                    if(InstanciaADMIN.Bot.bootAgregarEliminarActualizar(query) == true){
//                       Alerta("Registrado con exito");
//                       limpiar();
//                       
//                    }else{
//                       Alerta("Error de registro");
//                    }
//                }else  
//                    Alerta("El usuario ya existe");
//                    limpiar();
//            }else{
//                Alerta("El usuario ya existe");
//                limpiar();
//            }        
//        }else{
//            Alerta("Las contraseñas no coinciden");
//        }       
//    }
    private void limpiar(){
        TxtUser.setText("");
        TxtTel.setText("");
        PassField.setText("");
        PassFieldC.setText("");
        
    }
    public void Alerta(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialShadow Out;
    private necesario.PassField PassField;
    private necesario.PassField PassFieldC;
    private RSMaterialComponent.RSButtonMaterialTwo RegistrarYvalidar;
    private necesario.TextField TxtTel;
    private necesario.TextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private RSMaterialComponent.RSTextFieldIconTwo rSTextFieldIconTwo1;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial1;
    private RSMaterialComponent.RSTextFieldTwo rSTextFieldTwo1;
    // End of variables declaration//GEN-END:variables
}
